---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: beblue-thinkpad
# description will be included in the image's metadata
description: bebebeba.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      copr:
        - trixieua/mutter-patched
        - trixieua/mesa-clang
        - trixieua/morewaita-icon-theme
        - bieszczaders/kernel-cachyos-addons
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc

  - type: dnf
    install:
      packages:
        - adw-gtk3-theme
        - android-tools
        - audacious
        - code
        - distrobox
        - fastfetch
        - gparted
        - htop
        - irqbalance
        - morewaita-icon-theme
        - sysfsutils
        - scx-scheds
        - wireguard-tools
        - zcfan
        - nmap
      
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-classic-session

  - type: dnf
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:trixieua:mutter-patched
        skip-unavailable: true
        packages:
          - mutter
          - mutter-common
          - gdm
          - gnome-shell
          - gnome-shell-common
          - xorg-x11-server-Xwayland

  - type: dnf
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:trixieua:mesa-clang
        skip-unavailable: true
        packages:
          - mesa-filesystem
          - mesa-libgbm
          - mesa-dri-drivers
          - mesa-libEGL
          - mesa-libGL
          - mesa-vulkan-drivers
          - mesa-va-drivers

  - type: kargs
    arch: x86_64
    kargs:
      - thinkpad_acpi.fan_control=1
      - mitigations=off

  - type: systemd
    system:
      enabled:
        - zcfan.service
        - irqbalance.service
       # - scx.service

  - type: gnome-extensions
    install:
      - 517 # Caffeine
      - 3733 # Tiling Assistant
      - 6807 # System Monitor

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
